name: Deploy to Server

on:
  push:
    branches:
      - main # A ação será disparada quando houver um push no branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build
