name: Deploy to Server

on:
  push:
    branches:
      - main # A ação será disparada quando houver um push no branch main


  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Configurando Node
          uses: actions/setup-node@v2
          with:
            node-version: "22"

        - name: Instalando dependencias
          run: npm install

        - name: Test
          run: npm test
